coverage:
  status:
    project:
      default:
        target: 70% # Set your desired coverage target
        threshold: 2% # Allow coverage to drop by 2% while still passing
    patch:
      default:
        target: 70% # Coverage target for new code

ignore:
  - src/tests/
  - src/constants/
  - src/types/
  - src/errors/
  - src/utils/

# Optional: Configure which files to include (whitelist instead of blacklist)
fixes:
  - '::src/' # Map root coverage to src/ directory

# Optional: Configure comment behavior on PRs
comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false # If true, only post if coverage changes
  require_base: false # Must have a base coverage file
  require_head: true # Must have a head coverage file
