import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Using autogenerated sidebars for now - will be customized as we add more docs
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
