import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        'api/bi-map',
        'api/binary-heap',
        'api/deque',
        'api/doubly-linked-list',
        'api/linked-list',
        'api/lru-cache',
        'api/priority-queue',
        'api/queue',
        'api/red-black-tree',
        'api/sorted-map',
        'api/trie',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'examples' }],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
  ],
};

export default sidebars;
